version: '3.7'

services:
  save_tech_postgres:
    container_name: save_tech_postgres
    image: postgres
    ports:
      - 5440:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
